---
title: "BronxHousingData"
author: "Chris Woodard, Nathan Mowat, Saloman Gilles, Jessica Wheeler"
date: "June 1, 2016"
output: 
  html_document:
    keep_md: true
---

<br>

>We used the [Rolling Housing Sales for NYC](http://www1.nyc.gov/home/search/index.page?search-terms=Rolling+sales+update) website and looked at the Bronx dataset for analysis.

* The first steps towards analysis are loading the datafile and then cleaning the datafile.  Once the data is cleaned, we were able to analyze some data on housing trends in the Bronx.

###Getting Started - Loading the datafile:
```{r echo=TRUE, eval=TRUE}

## @knitr dataLoader

#this file contains coed for reading in the data to analyse
#---------------------------------------------------------------------------------------
# this file contains code for for reading in the data file for analysis               --
#---------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------
### NOTE : must be loaded first                                                       --
### ------------------------------------------------------------------------------------

#STEP 1: DOWNLOAD PACKAGES AND LOAD THEM.
require(gdata)
require(plyr)


#STEP 2: GET DATA INTO R FROM DROPBOX
setwd("/Users/JessicaSibal/Dropbox/Wk3Bronx")
bx <- read.csv("/Users/JessicaSibal/Dropbox/Wk3Bronx/Data/rollingsales_bronx.csv",skip=4,header=TRUE)
```

```{r, echo=TRUE, eval=FALSE}
#STEP 3: CHECK DATA
head(bx)
summary(bx)
str(bx)
```



###Cleaning the Bronx datafile:
```{r echo=TRUE, eval=TRUE }
## @knitr dataCleaner

#---------------------------------------------------------------------------------------
# this file contains code for cleaning the data to analyse                            --
#---------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------
### NOTE : must load after LoadDataFile.R before it works after necessary libraries   --
### ------------------------------------------------------------------------------------

#STEP 4: CLEAN DATA
bx$SALE.PRICE.N <- as.numeric(gsub("[^[:digit:]]","", bx$SALE.PRICE)) #Changes SALE.PRICE to numeric, and cleans it up creating a new variable
count(is.na(bx$SALE.PRICE.N)) #Counts all the NA's in the dataset under SALE.PRICE.N
names(bx) <- tolower(names(bx)) #Changes all column names to lower case
bx$gross.sqft <- as.numeric(gsub("[^[:digit:]]","", bx$gross.square.feet)) #Gets rid of leading digits
bx$land.sqft <- as.numeric(gsub("[^[:digit:]]","", bx$land.square.feet)) #Gets rid of leading digits
bx$sale.date <- as.Date(bx$sale.date) # Changes sale.date to date format in R
bx$year.built <- as.numeric(as.character(bx$year.built)) #Changes variable to numeric from factor

```


###Bronx Data Analysis:
```{r, echo=TRUE, eval=TRUE}
## @knitr dataAnalyser

#---------------------------------------------------------------------------------------
#    this file contains analysis, includes histograms, plots, summary                 -- 
#---------------------------------------------------------------------------------------
### ------------------------------------------------------------------------------------
### NOTE : must load after cleanDataFile.R before it works after necessary libraries  --
### ------------------------------------------------------------------------------------

#STEP 5: VISUALIZE DATA OF SALES AND GROSS.SQFT
attach(bx)
hist(sale.price.n) # regular histogram of the data, doesn't look right.
hist(sale.price.n[sale.price.n>0]) #noticed over 15,000 missing data (or NA's) for sales.price.n
detach(bx)

bx.sale <- bx[bx$sale.price.n!=0,] #Keeping only the actual sales: DOESNT GET RID OF NA's, NOT ZEROES IN DATA SET, THEY ARE DASHES (-)
plot(bx.sale$gross.sqft,bx.sale$sale.price.n) #ScatterPlot of gross.sqft (on x-axis) vs sale.price.n (on y-axis)

#STEP 6: LOOK AT 1-3 FAMILY HOMES
bx.homes <- bx.sale[which(grepl("FAMILY",bx.sale$building.class.category)),] 
dim(bx.homes) # shows 2589 Rows and 24 Columns
plot(log(bx.homes$gross.sqft),log(bx.homes$sale.price.n)) #Plot of Log transform of gross.sqft and sale.price.n
summary(bx.homes[which(bx.homes$sale.price.n<100000),]) #Summary of sale.price.n below $100,000


#STEP 7: REMOVE OUTLIERS THAT DON'T SEEM LIKE ACTUAL SALES
bx.homes$outliers <- (log(bx.homes$sale.price.n) <=5) + 0 #Removed the log data that was less than 5
bx.homes <- bx.homes[which(bx.homes$outliers==0),] 
plot(log(bx.homes$gross.sqft),log(bx.homes$sale.price.n)) #ScatterPlot of Log gross.sqft vs sale.price.n with outliers removed

# Based on the log plot of gross square feet and sale price, it seems that Gross square footage is not a good indicator of sale price based on the spread of the data.

plot(bx.homes$building.class.category, bx.homes$sale.price.n)

#The 1 family homes have less variance as can be seen by the boxplot but they have a lot of outliers as well.  The 1-family homes could encompass low or wealthy areas in cities which could account for all of the outliers observed.  In the 2-family and 3-family homes, there is a bit more variance as the spread of the data is larger. 
```

