---
title: "BronxHousingData"
author: "Chris Woodard, Nathan Mowat, Saloman Gilles, Jessica Wheeler"
date: "June 1, 2016"
output: 
  html_document:
    keep_md: true
---

<br>

>We used the [Rolling Housing Sales for NYC](http://www1.nyc.gov/home/search/index.page?search-terms=Rolling+sales+update) website and looked at the Bronx dataset for analysis.

* The first steps towards analysis are loading the datafile and then cleaning the datafile.  Once the data is cleaned, we were able to analyze some data on housing trends in the Bronx.

###Getting Started - Loading the datafile:

```{r, code=readLines ("/Users/JessicaSibal/Dropbox/Wk3Bronx/Analysis/LoadDataFile.R"), echo=TRUE, eval=FALSE}
```


###Cleaning the Bronx datafile:
```{r, code=readLines ("/Users/JessicaSibal/Dropbox/Wk3Bronx/Analysis/CleanDataFile.R"), echo=TRUE, eval=FALSE}
```

###Bronx Data Analysis:
```{r, code=readLines ("/Users/JessicaSibal/Dropbox/Wk3Bronx/Analysis/Analysis.R"), echo=TRUE, eval=FALSE}
```

```{r, echo=FALSE}


```